// <autogenerated>
//   This file was generated from T4 template
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>
using Swashbuckle.AspNetCore.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using TeamSystem.AlyCE.Services.Common.DTO;
using TeamSystem.AlyCE.Services.FW_Extendibility.DTO;

namespace TeamSystem.Alyante.Services.FI_GeneralData.DTO
{
    [DataContract(Namespace = "")]
    public class RegioneResultDTO : BaseDTO
    {
        [DataMember]
        public List<int> Regione { get; set; }

    }
}


